work day part:
    cargo watch -x "check -p {{day}}" -s "just test {{day}} {{part}}"
create day:
    cargo generate --path ./daily-template --name {{day}}
test day part:
    cargo nextest run -p {{day}} {{part}}
