work day part:
    cargo watch -x "check -p {{day}}" -s "just test {{part}}"
create day:
    cargo generate --path ./daily-template --name {{day}}
test part +FLAGS='-p day-01':
    cargo nextest run {{FLAGS}} {{part}}
